### ISSUE TITLE
Color to be changed to #707070

### ISSUE THREAD

**Issue by saieshv** [saieshv/Dispute#10]
![Screenshot 2022-05-04 at 10 27 00 AM](https://user-images.githubusercontent.com/81156455/166625130-f83ce098-c92b-4fe8-b529-415ed683cf37.png)

**Comment by MamataNivajekar** [comment]
@saieshv The color is set to #ACACAC as per the design, please confirm the above changes.

![image](https://user-images.githubusercontent.com/81617777/166625899-1fb5b86c-90bb-4203-8905-142d81acf1f5.png)

**Comment by saieshv** [comment]
yes , for mobile text color is #707070

**Comment by MamataNivajekar** [comment]
Text color changed to #707070 (mobile)
