### ISSUE TITLE
Optical alignment , add some px padding on top so that it looks balanced

### ISSUE THREAD

**Issue by saieshv** [saieshv/Dispute#4]
![Screenshot 2022-05-02 at 1 37 39 PM](https://user-images.githubusercontent.com/81156455/166203884-dab24479-75b6-41ae-84fe-9aa0ab7ab360.png)

**Comment by saieshv** [comment]
left is figma , right img is web page

**Comment by MamataNivajekar** [comment]
@saieshv couldn't replicate the above issue. optical alignment is vertically centered. you can check the below screenshots.

![image](https://user-images.githubusercontent.com/81617777/166222191-36749f69-057e-49b8-bd9f-45cafcfa428a.png)
![image](https://user-images.githubusercontent.com/81617777/166222264-5e1112eb-5e95-45e3-a1b9-c71062f726fe.png)

**Comment by saieshv** [comment]
yes this looks balanced , Thanks
