### ISSUE TITLE
TICKET details page timeline spacing 

### ISSUE THREAD

**Issue by saieshv** [saieshv/Dispute#8]
![Screenshot 2022-05-03 at 11 33 22 AM](https://user-images.githubusercontent.com/81156455/166410642-0a6a9157-8ec7-4062-be1d-e5c6ad0760d4.png)
The current spacing between 2 status labels is 14px, which is to be kept 20px

https://www.figma.com/file/0hkrYadmvcXkOziXL5KVwN/Dispute-v2?node-id=758%3A2222

**Comment by saieshv** [comment]
Similarly for mobile ui also 20px spacing between each. point

**Comment by MamataNivajekar** [comment]
@saieshv The current spacing between 2 status labels is already 20px, you can check the below screenshot.

![image](https://user-images.githubusercontent.com/81617777/166412365-435f9f65-99a4-45f4-b89c-0f3b7a99e309.png)
